export const AUTH = {
  LOGIN: "AUTH_LOGIN",
  LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  LOGIN_FAILURE: "AUTH_LOGIN_FAILURE",
  LOGOUT: "AUTH_LOGOUT"
}

export const SALES = {
  SEARCH: "SALES_SEARCH",
  REGISTER: "SALES_REGISTER",
  POST: "SALES_POST",
  PUT: "SALES_PUT",
  DELETE: "SALES_DELETE",
  GET: "SALES_GET"
}